name: Preprocessing Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install pandas numpy scikit-learn Sastrawi nltk

    - name: Run Automation Preprocessing
      run: |
        python "Eksperimen_SML_Ridho-nur-mahmudah/preprocessing/automate_Ridho-nur-mahmudah.py"

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        # Perintah ini hanya akan jalan jika ada perubahan file (data baru)
        git commit -m "Update preprocessed data [skip ci]" || echo "No changes to commit"
        git push